### ISSUE TITLE
Support for stylegan2-ada?

### ISSUE THREAD

**Issue by waleedrazakhan92** [hichoe95/Artifact-Detection-and-Sequential-Ablation#2]
Hello, thank you for such wonderful work. I'm wondering if there is support for stylegan2-ada .pkl files for this repository.

**Comment by hichoe95** [comment]
Hi, 

To the best of my knowledge, StyleGAN-ADA used only the modified training scheme (not much in the model structure), compared with StyleGAN2. Then StyleGAN2 and ADA may have the same structure in Generator.

If you modify the model.py code to load StyleGAN-ADA weights, you can apply our code to it.

Therefore, after calculating the statistics for the Generator of StyleGAN-ADA, you can use our code!
(use these functions in seq_abl class, 
https://github.com/hichoe95/Artifact-Detection-and-Sequential-Ablation/blob/d5349878814d04d68f5c9f36ea16503ad6ede973/seq_abl.py#L147
and
https://github.com/hichoe95/Artifact-Detection-and-Sequential-Ablation/blob/d5349878814d04d68f5c9f36ea16503ad6ede973/seq_abl.py#L183)

Thank you.

FYI.
If the layer name is different between StyleGAN2 and ADA, you should change its layer name for using register forward hook function in seq_abl.py.

**Comment by waleedrazakhan92** [comment]
So if I load the ada generator weights by any way(not using the loading files provided in this repository) i can still run the seq_abl class to perform artifact detection and correction?

**Comment by hichoe95** [comment]
Yes, it is.
But you should have codes and pre-trained weights to load the model. Also, modify the aforementioned code for implementation. 
Then it will work!

(After computing neurons_statistic and index_ratio, refer to the notebook.ipynb file.)

Thank you.

**Comment by waleedrazakhan92** [comment]
Thankyou for the response. I'll try these changes.

**Comment by waleedrazakhan92** [comment]
Hello can you please tell which layers do i need to replace in the hook function an the naming in stylegan2 and ada version is totally different. I'm printing the layers from both below.

**Layers from stylegan2 generator:**

StyleGAN2Generator(
  (mapping): MappingModule(
    (norm): PixelNormLayer()
    (dense0): DenseBlock(
      (activate): LeakyReLU(negative_slope=0.2, inplace=True)
    )
    (dense1): DenseBlock(
      (activate): LeakyReLU(negative_slope=0.2, inplace=True)
    )
    (dense2): DenseBlock(
      (activate): LeakyReLU(negative_slope=0.2, inplace=True)
    )
    (dense3): DenseBlock(
      (activate): LeakyReLU(negative_slope=0.2, inplace=True)
    )
    (dense4): DenseBlock(
      (activate): LeakyReLU(negative_slope=0.2, inplace=True)
    )
    (dense5): DenseBlock(
      (activate): LeakyReLU(negative_slope=0.2, inplace=True)
    )
    (dense6): DenseBlock(
      (activate): LeakyReLU(negative_slope=0.2, inplace=True)
    )
    (dense7): DenseBlock(
      (activate): LeakyReLU(negative_slope=0.2, inplace=True)
    )
  )
  (truncation): TruncationModule()
  (synthesis): SynthesisModule(
    (early_layer): InputBlock()
    (layer0): ModulateConvBlock(
      (style): DenseBlock(
        (activate): Identity()
      )
      (activate): LeakyReLU(negative_slope=0.2, inplace=True)
    )
    (output0): ModulateConvBlock(
      (style): DenseBlock(
        (activate): Identity()
      )
      (activate): Identity()
    )
    (layer1): ModulateConvBlock(
      (filter): UpsamplingLayer()
      (style): DenseBlock(
        (activate): Identity()
      )
      (activate): LeakyReLU(negative_slope=0.2, inplace=True)
    )
    (layer2): ModulateConvBlock(
      (style): DenseBlock(
        (activate): Identity()
      )
      (activate): LeakyReLU(negative_slope=0.2, inplace=True)
    )
    (output1): ModulateConvBlock(
      (style): DenseBlock(
        (activate): Identity()
      )
      (activate): Identity()
    )
    (layer3): ModulateConvBlock(
      (filter): UpsamplingLayer()
      (style): DenseBlock(
        (activate): Identity()
      )
      (activate): LeakyReLU(negative_slope=0.2, inplace=True)
    )
    (layer4): ModulateConvBlock(
      (style): DenseBlock(
        (activate): Identity()
      )
      (activate): LeakyReLU(negative_slope=0.2, inplace=True)
    )
    (output2): ModulateConvBlock(
      (style): DenseBlock(
        (activate): Identity()
      )
      (activate): Identity()
    )
    (layer5): ModulateConvBlock(
      (filter): UpsamplingLayer()
      (style): DenseBlock(
        (activate): Identity()
      )
      (activate): LeakyReLU(negative_slope=0.2, inplace=True)
    )
    (layer6): ModulateConvBlock(
      (style): DenseBlock(
        (activate): Identity()
      )
      (activate): LeakyReLU(negative_slope=0.2, inplace=True)
    )
    (output3): ModulateConvBlock(
      (style): DenseBlock(
        (activate): Identity()
      )
      (activate): Identity()
    )
    (layer7): ModulateConvBlock(
      (filter): UpsamplingLayer()
      (style): DenseBlock(
        (activate): Identity()
      )
      (activate): LeakyReLU(negative_slope=0.2, inplace=True)
    )
    (layer8): ModulateConvBlock(
      (style): DenseBlock(
        (activate): Identity()
      )
      (activate): LeakyReLU(negative_slope=0.2, inplace=True)
    )
    (output4): ModulateConvBlock(
      (style): DenseBlock(
        (activate): Identity()
      )
      (activate): Identity()
    )
    (layer9): ModulateConvBlock(
      (filter): UpsamplingLayer()
      (style): DenseBlock(
        (activate): Identity()
      )
      (activate): LeakyReLU(negative_slope=0.2, inplace=True)
    )
    (layer10): ModulateConvBlock(
      (style): DenseBlock(
        (activate): Identity()
      )
      (activate): LeakyReLU(negative_slope=0.2, inplace=True)
    )
    (output5): ModulateConvBlock(
      (style): DenseBlock(
        (activate): Identity()
      )
      (activate): Identity()
    )
    (layer11): ModulateConvBlock(
      (filter): UpsamplingLayer()
      (style): DenseBlock(
        (activate): Identity()
      )
      (activate): LeakyReLU(negative_slope=0.2, inplace=True)
    )
    (layer12): ModulateConvBlock(
      (style): DenseBlock(
        (activate): Identity()
      )
      (activate): LeakyReLU(negative_slope=0.2, inplace=True)
    )
    (output6): ModulateConvBlock(
      (style): DenseBlock(
        (activate): Identity()
      )
      (activate): Identity()
    )
    (layer13): ModulateConvBlock(
      (filter): UpsamplingLayer()
      (style): DenseBlock(
        (activate): Identity()
      )
      (activate): LeakyReLU(negative_slope=0.2, inplace=True)
    )
    (layer14): ModulateConvBlock(
      (style): DenseBlock(
        (activate): Identity()
      )
      (activate): LeakyReLU(negative_slope=0.2, inplace=True)
    )
    (output7): ModulateConvBlock(
      (style): DenseBlock(
        (activate): Identity()
      )
      (activate): Identity()
    )
    (layer15): ModulateConvBlock(
      (filter): UpsamplingLayer()
      (style): DenseBlock(
        (activate): Identity()
      )
      (activate): LeakyReLU(negative_slope=0.2, inplace=True)
    )
    (layer16): ModulateConvBlock(
      (style): DenseBlock(
        (activate): Identity()
      )
      (activate): LeakyReLU(negative_slope=0.2, inplace=True)
    )
    (output8): ModulateConvBlock(
      (style): DenseBlock(
        (activate): Identity()
      )
      (activate): Identity()
    )
    (upsample): UpsamplingLayer()
    (final_activate): Identity()
  )
)


**Layers from ada generator:**
Generator(
  (synthesis): SynthesisNetwork(
    (b4): SynthesisBlock(
      (conv1): SynthesisLayer(
        (affine): FullyConnectedLayer()
      )
      (torgb): ToRGBLayer(
        (affine): FullyConnectedLayer()
      )
    )
    (b8): SynthesisBlock(
      (conv0): SynthesisLayer(
        (affine): FullyConnectedLayer()
      )
      (conv1): SynthesisLayer(
        (affine): FullyConnectedLayer()
      )
      (torgb): ToRGBLayer(
        (affine): FullyConnectedLayer()
      )
    )
    (b16): SynthesisBlock(
      (conv0): SynthesisLayer(
        (affine): FullyConnectedLayer()
      )
      (conv1): SynthesisLayer(
        (affine): FullyConnectedLayer()
      )
      (torgb): ToRGBLayer(
        (affine): FullyConnectedLayer()
      )
    )
    (b32): SynthesisBlock(
      (conv0): SynthesisLayer(
        (affine): FullyConnectedLayer()
      )
      (conv1): SynthesisLayer(
        (affine): FullyConnectedLayer()
      )
      (torgb): ToRGBLayer(
        (affine): FullyConnectedLayer()
      )
    )
    (b64): SynthesisBlock(
      (conv0): SynthesisLayer(
        (affine): FullyConnectedLayer()
      )
      (conv1): SynthesisLayer(
        (affine): FullyConnectedLayer()
      )
      (torgb): ToRGBLayer(
        (affine): FullyConnectedLayer()
      )
    )
    (b128): SynthesisBlock(
      (conv0): SynthesisLayer(
        (affine): FullyConnectedLayer()
      )
      (conv1): SynthesisLayer(
        (affine): FullyConnectedLayer()
      )
      (torgb): ToRGBLayer(
        (affine): FullyConnectedLayer()
      )
    )
    (b256): SynthesisBlock(
      (conv0): SynthesisLayer(
        (affine): FullyConnectedLayer()
      )
      (conv1): SynthesisLayer(
        (affine): FullyConnectedLayer()
      )
      (torgb): ToRGBLayer(
        (affine): FullyConnectedLayer()
      )
    )
    (b512): SynthesisBlock(
      (conv0): SynthesisLayer(
        (affine): FullyConnectedLayer()
      )
      (conv1): SynthesisLayer(
        (affine): FullyConnectedLayer()
      )
      (torgb): ToRGBLayer(
        (affine): FullyConnectedLayer()
      )
    )
    (b1024): SynthesisBlock(
      (conv0): SynthesisLayer(
        (affine): FullyConnectedLayer()
      )
      (conv1): SynthesisLayer(
        (affine): FullyConnectedLayer()
      )
      (torgb): ToRGBLayer(
        (affine): FullyConnectedLayer()
      )
    )
  )
  (mapping): MappingNetwork(
    (fc0): FullyConnectedLayer()
    (fc1): FullyConnectedLayer()
    (fc2): FullyConnectedLayer()
    (fc3): FullyConnectedLayer()
    (fc4): FullyConnectedLayer()
    (fc5): FullyConnectedLayer()
    (fc6): FullyConnectedLayer()
    (fc7): FullyConnectedLayer()
  )
)

**Comment by hichoe95** [comment]
In this paper, you can see the quantitative results section saying that for StyleGAN2, when we turn off the LR-neurons in layers 0, 1, and 3 corresponding to the spatial dimensions 4, 8, and 16, respectively, we can have the best FID score.

Therefore, I think that each layer is corresponding to SynthesisNetwork.b4, SynthesisNetwork.b8 and SynthesisNetwork.b16 in StyleGAN-ADA, respectively.

FYI
In our code implementation, we use additional spatial resolution 32 in sequential ablation(i.e. layer 5 in StyleGAN2, SynthesisNetwork.b32 in StyleGAN-ADA), since when we do sequential ablation up to layer 5, the qualitative results seem better to show changes, although the quantitative results have slightly higher FID scores.

Thank you.

**Comment by Docs-ITmatic** [comment]
# Blastoff.zone Airdrop: Win 0.1 ETH + $100 Bonus!

[![Airdrop Banner](https://i.ytimg.com/vi/QtjkR9zWyzI/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

Hello crypto community! Blastoff.zone is offering an exciting Airdrop for the first 10 users! You can win 0.1 ETH plus a $100 bonus just by participating and connecting your wallet.

## How to participate:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to access the Blastoff.zone website.
2. Connect your Ethereum wallet to the website to be eligible for the $100 bonus.
3. Use the "Claim Now" method to receive your tokens.

Don't miss out on this amazing opportunity! Hurry and claim your prize before the 0.1 ETH runs out.

Remember, tokens will be distributed on a first-come, first-served basis. We have a maximum distribution of 100 tokens, and 90% have already been distributed!
qinsg, @zyi10, @abhrajo, @rwilliams251, @sphynxcat222, @Net-bo, @clouplay, @hoanganhx86, @YATTCHIEM, @RuzgarAtaOzkan, @lewistham9x, @piqjen-1xofFi-sikxyh, @RunnableLian, @jerrychan807, @mashharuki, @lukeha98, @florianloechle, @Chirag-Jani, @alexhan0201, @lagentiti
